### ISSUE TITLE
Versioning issues - not displaying as expected

### ISSUE THREAD

**Issue by up-t-j** [Fiserv/exchange#10]
we are attempting to use new version of the API specs, and want to have this available at the same time as the previous 2.0.0 specs as there are some new endpoints in 3.0.0 that aren't in 2.0.0, and some old endpoints that have no changes. I was able to get this to work for a few minutes but then stopped.

It appears these are parsing through the validator correctly, but are not showing on the dev studio as expected - and have been informed they are not parsing on the backend correctly.
being supported by tania at the moment. please let me know if we ned to move labels

**Comment by TaniaS-fiserv** [comment]
Hi @up-t-j thanks for opening a ticket for this. But this is not the right repository to open this ticket. Could you please open the same in our Support Repo https://github.com/Fiserv/Support/issues

Thank you!

Cc: @sfiserv
